### ISSUE TITLE
Profile Page (Misc Info) Feature

### ISSUE THREAD

**Issue by samuelloh** [CS2103JAN2018-W09-B3/main#35]
**Description:**
Add a unique profile page for each student in the contact list. Includes additional information not being displayed on the student card. Examples are: "Emergency Contact" and a Profile Picture. This page is called using a command typed in the command input box and is displayed on the browser panel.

**Motivation:**
With this, tutors are able to store more misc information about students without having these information be crowded into a student card. Also, makes information about each student more readable instead of only through the student card. Several misc are important information, although not used often. Example: Emergency contact is important should any issues happen to the student. However, it is not used very often.

**Comment by yapni** [comment]
Resolve in v1.5 release
